server:
  port: 8083

app:
  name: "Billing Service"
  greeting: "Billing Service at your service!"

spring:
  datasource:
    url: jdbc:mysql//localhost:3306/billingdb
    username: root
    password: root

managament:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
