server:
  port: 8082

app:
  name: "Order Service"
  greeting: "Hello from Order Service!"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
