server:
  port: 8081

app:
  name: "User Service"
  greeting: "Hi from User Service Configuration!"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
